export const blogPageContent = {
  hero: {
    badge: 'Our Journal',
    title: 'Insights & Perspectives',
    description: 'Exploring the intersections of strategy, global culture, and technical innovation. Written by the thinkers at Kaarshe.',
  },
  featured: {
    id: 'featured-1',
    category: 'Strategy',
    isFeatured: true,
    title: 'The Future of Digital Sovereignty in a Post-Global Era',
    description: 'An in-depth look at how decentralized systems are reshaping global digital governance and personal data privacy in the modern era.',
    author: {
      name: 'Marcus Thorne',
      role: 'Managing Director, Policy Strategy',
      image: '/images/authors/marcus-thorne.jpg',
    },
    date: 'Oct 24, 2023',
    readTime: '12 min read',
    image: '/images/blog/digital-sovereignty.jpg',
    slug: 'future-of-digital-sovereignty',
  },
  categories: [
    { label: 'All', value: 'all', active: true },
    { label: 'Strategy', value: 'strategy', active: false },
    { label: 'Engineering', value: 'engineering', active: false },
    { label: 'Culture', value: 'culture', active: false },
  ],
  posts: [
    {
      id: '1',
      category: 'Engineering',
      title: 'Why Modern Infrastructure Requires a Culture of Reliability',
      excerpt: 'Exploring the link between high-availability systems and the psychological safety of engineering teams.',
      date: 'Oct 20, 2023',
      readTime: '6 min read',
      image: '/images/blog/reliability-culture.jpg',
      slug: 'modern-infrastructure-reliability-culture',
    },
    {
      id: '2',
      category: 'Culture',
      title: 'The Anthropology of Hybrid Workspaces',
      excerpt: 'How physical and digital environments influence the evolution of corporate identity and social norms.',
      date: 'Oct 18, 2023',
      readTime: '8 min read',
      image: '/images/blog/hybrid-workspaces.jpg',
      slug: 'anthropology-hybrid-workspaces',
    },
    {
      id: '3',
      category: 'Strategy',
      title: 'Leveraging Low-Latency Decision Engines',
      excerpt: 'The strategic advantage of real-time data processing in competitive financial markets and logistical networks.',
      date: 'Oct 15, 2023',
      readTime: '5 min read',
      image: '/images/blog/decision-engines.jpg',
      slug: 'leveraging-low-latency-decision-engines',
    },
    {
      id: '4',
      category: 'Engineering',
      title: 'Next-Gen Hardware: Beyond the Silicon Limit',
      excerpt: 'What happens when traditional computing reaches its thermal and physical boundaries?',
      date: 'Oct 12, 2023',
      readTime: '10 min read',
      image: '/images/blog/next-gen-hardware.jpg',
      slug: 'next-gen-hardware-beyond-silicon',
    },
    {
      id: '5',
      category: 'Design',
      title: 'The Aesthetics of Utility: A New Design Paradigm',
      excerpt: 'Moving away from minimalism toward a functionalism that celebrates complexity and craftsmanship.',
      date: 'Oct 09, 2023',
      readTime: '4 min read',
      image: '/images/blog/aesthetics-utility.jpg',
      slug: 'aesthetics-utility-new-design',
    },
    {
      id: '6',
      category: 'Strategy',
      title: 'Global Supply Chains in a Fragmenting World',
      excerpt: 'How resilient organizations are rethinking logistics in the face of geopolitical shifts and climate risks.',
      date: 'Oct 05, 2023',
      readTime: '9 min read',
      image: '/images/blog/supply-chains.jpg',
      slug: 'global-supply-chains-fragmenting-world',
    },
  ],
}